name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the site
      run: |
        # Add your build commands here if necessary
        # For example, if you're using a static site generator like Jekyll, Hugo, etc.
        # npm install && npm run build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./path/to/your/build/output  # Change this to your output directory
